#!/bin/python3

import math
import os
import random
import re
import sys



def utopianTree(n):
    height = 1
    for i in range(1, n + 1):
        if i % 2 != 0:
            height *= 2
        else:
            height += 1
            
    return height

if __name__ == '__main__':
    output_path = os.environ.get('OUTPUT_PATH')
    if output_path:
        fptr = open(output_path, 'w')
    else:
        fptr = sys.stdout

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    if output_path:
        fptr.close()

